export interface ItemDef {
  id: string;
  name: string;
  description: string;
  type: 'weapon' | 'tool' | 'consumable' | 'quest' | 'material' | 'armor';
  equipSlot?: 'weapon' | 'lantern' | 'accessory';
  stats?: { damage?: number; defense?: number };
  stackable: boolean;
  maxStack: number;
  value?: number; // base gold value for trading (buy price; sell = floor(value / 2))
}

export interface InventorySlot {
  itemId: string;
  quantity: number;
}

export const ITEMS: Record<string, ItemDef> = {
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    description: 'A simple wooden training sword. Better than nothing.',
    type: 'weapon',
    equipSlot: 'weapon',
    stats: { damage: 5 },
    stackable: false,
    maxStack: 1,
    value: 10,
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'A sturdy iron blade forged by Erik.',
    type: 'weapon',
    equipSlot: 'weapon',
    stats: { damage: 12 },
    stackable: false,
    maxStack: 1,
    value: 60,
  },
  enchanted_blade: {
    id: 'enchanted_blade',
    name: 'Enchanted Blade',
    description: 'A blade imbued with arcane energy. Glows faintly in the dark.',
    type: 'weapon',
    equipSlot: 'weapon',
    stats: { damage: 20 },
    stackable: false,
    maxStack: 1,
    value: 200,
  },
  stone_axe: {
    id: 'stone_axe',
    name: 'Stone Axe',
    description: 'A crude axe made from stone and wood. Decent for chopping.',
    type: 'weapon',
    equipSlot: 'weapon',
    stats: { damage: 8 },
    stackable: false,
    maxStack: 1,
    value: 25,
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    description: 'Light armor made from tanned hides. Offers basic protection.',
    type: 'armor',
    equipSlot: 'accessory',
    stats: { defense: 5 },
    stackable: false,
    maxStack: 1,
    value: 40,
  },
  iron_shield: {
    id: 'iron_shield',
    name: 'Iron Shield',
    description: 'A sturdy iron shield. Reduces incoming damage.',
    type: 'armor',
    equipSlot: 'accessory',
    stats: { defense: 10 },
    stackable: false,
    maxStack: 1,
    value: 80,
  },
  lantern: {
    id: 'lantern',
    name: 'Lantern',
    description: 'An old brass lantern. Essential for dark places.',
    type: 'tool',
    equipSlot: 'lantern',
    stackable: false,
    maxStack: 1,
    value: 30,
  },
  rope: {
    id: 'rope',
    name: 'Rope',
    description: 'A sturdy length of rope. Useful for climbing and descending.',
    type: 'tool',
    stackable: false,
    maxStack: 1,
    value: 20,
  },
  herb_pouch: {
    id: 'herb_pouch',
    name: 'Herb Pouch',
    description: 'A leather pouch for collecting and storing herbs.',
    type: 'tool',
    stackable: false,
    maxStack: 1,
    value: 15,
  },
  health_potion: {
    id: 'health_potion',
    name: 'Health Potion',
    description: 'A restorative brew made from forest herbs. Heals 40 HP.',
    type: 'consumable',
    stackable: true,
    maxStack: 10,
    value: 25,
  },
  blight_ward: {
    id: 'blight_ward',
    name: 'Blight Ward',
    description: 'A protective charm that reduces Blight damage. Faintly warm.',
    type: 'consumable',
    stackable: true,
    maxStack: 5,
    value: 50,
  },
  provisions: {
    id: 'provisions',
    name: 'Provisions',
    description: 'Dried meat and bread. Restores 20 HP over time.',
    type: 'consumable',
    stackable: true,
    maxStack: 20,
    value: 8,
  },
  raw_iron: {
    id: 'raw_iron',
    name: 'Raw Iron',
    description: 'Unrefined iron ore. Erik can forge this into something useful.',
    type: 'material',
    stackable: true,
    maxStack: 20,
    value: 12,
  },
  wood: {
    id: 'wood',
    name: 'Wood',
    description: 'A bundle of sturdy wood. Used for crafting and building.',
    type: 'material',
    stackable: true,
    maxStack: 30,
    value: 5,
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    description: 'A chunk of hard stone. Useful for tools and construction.',
    type: 'material',
    stackable: true,
    maxStack: 30,
    value: 4,
  },
  leather: {
    id: 'leather',
    name: 'Leather',
    description: 'Tanned animal hide. Used for armor and pouches.',
    type: 'material',
    stackable: true,
    maxStack: 20,
    value: 10,
  },
  plant_fiber: {
    id: 'plant_fiber',
    name: 'Plant Fiber',
    description: 'Tough fibers harvested from forest plants. Used for rope and cloth.',
    type: 'material',
    stackable: true,
    maxStack: 30,
    value: 3,
  },
  glass_vial: {
    id: 'glass_vial',
    name: 'Glass Vial',
    description: 'An empty vial suitable for holding potions.',
    type: 'material',
    stackable: true,
    maxStack: 10,
    value: 8,
  },
  moonpetal: {
    id: 'moonpetal',
    name: 'Moonpetal',
    description: 'A rare flower that blooms only under moonlight. Willow needs these.',
    type: 'material',
    stackable: true,
    maxStack: 10,
    value: 20,
  },
  enchantment_dust: {
    id: 'enchantment_dust',
    name: 'Enchantment Dust',
    description: 'Shimmering arcane powder. Used to imbue weapons with magic.',
    type: 'material',
    stackable: true,
    maxStack: 5,
    value: 50,
  },
  wolf_pelt: {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    description: 'A grey pelt from a forest wolf. Can be tanned into leather.',
    type: 'material',
    stackable: true,
    maxStack: 10,
    value: 15,
  },
  runestone_forest: {
    id: 'runestone_forest',
    name: 'Forest Runestone',
    description: 'An ancient runestone recovered from the Forest Cave. Pulses with green light.',
    type: 'quest',
    stackable: false,
    maxStack: 1,
  },
  runestone_mine: {
    id: 'runestone_mine',
    name: 'Mine Runestone',
    description: 'An ancient runestone recovered from the Abandoned Mine. Glows with amber warmth.',
    type: 'quest',
    stackable: false,
    maxStack: 1,
  },
  runestone_tower: {
    id: 'runestone_tower',
    name: 'Tower Runestone',
    description: 'An ancient runestone recovered from the Ruined Tower. Crackles with violet energy.',
    type: 'quest',
    stackable: false,
    maxStack: 1,
  },
  aldric_journal_1: {
    id: 'aldric_journal_1',
    name: "Aldric's Journal (Part 1)",
    description: 'The first pages of Sage Aldric\'s journal. Mentions the Blight\'s origins.',
    type: 'quest',
    stackable: false,
    maxStack: 1,
  },
  aldric_journal_2: {
    id: 'aldric_journal_2',
    name: "Aldric's Journal (Part 2)",
    description: 'Journal entries about the Shrine of Dawn and its protective wards.',
    type: 'quest',
    stackable: false,
    maxStack: 1,
  },
  aldric_journal_3: {
    id: 'aldric_journal_3',
    name: "Aldric's Journal (Part 3)",
    description: 'Notes on the three runestone locations and their guardians.',
    type: 'quest',
    stackable: false,
    maxStack: 1,
  },
  aldric_journal_4: {
    id: 'aldric_journal_4',
    name: "Aldric's Journal (Part 4)",
    description: 'Aldric\'s research on the enchantments needed to combat the Blight.',
    type: 'quest',
    stackable: false,
    maxStack: 1,
  },
  aldric_journal_5: {
    id: 'aldric_journal_5',
    name: "Aldric's Journal (Part 5)",
    description: 'The final entry. Aldric writes of his departure into the Ancient Forest.',
    type: 'quest',
    stackable: false,
    maxStack: 1,
  },
  gold: {
    id: 'gold',
    name: 'Gold',
    description: 'The common currency of Thornwick and the surrounding lands.',
    type: 'material',
    stackable: true,
    maxStack: 9999,
  },
};
